name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the Project
      working-directory: ./faultybot
      run: |
        wget https://raw.githubusercontent.com/jplight/faultybot/main/.pylintrc
        pylint --rcfile=.pylintrc `ls -R|grep .py$|xargs`
    - name: Analysing the Settings
      run: |
        wget https://raw.githubusercontent.com/jplight/faultybot/main/.pylintrc
        pylint --rcfile=.pylintrc setup.py
